// The script. One object per page. Engine renders these in order.
// Page shape: see docs/SKILL.md "Page schema". Keep language simple: short sentences, no jargon.
export const CAREFUL = { 'Easy.':'Hmm.', 'Done.':'Done… I think.', 'Next.':'Next?', '…':'…', 'Wait.':'Wait. Wait.', 'Right?':'Right… right?', 'Oh no.':'Oh no. Oh no.' };

export const ISSUES = [
  { n: 1, title: 'Just Move the Button', tagline: 'A five-minute job', available: true },
  { n: 2, title: 'Just Add a Field', tagline: 'Who snaps?', available: false },
];

export const ISSUE = {
  number: 1, title: 'Just Move the Button', tagline: 'A five-minute job',
  ticket: `Tiny job! Move the <b>Submit</b> button to the <b>right</b>. Rename it <b>"Continue"</b>. 5 minutes?`,
};

export const PAGES = [
  { id: 'estimate', type: 'estimate',
    caps: ['Tuesday. 9:14 AM.'], pose: 'typing', think: 'Easy.',
    q: 'How long does this take?', choices: ['5 minutes', 'An hour', 'A day'],
  },
  { id: 'robot', type: 'guess', title: 'The Checker',
    p1: { cap: 'You rename it. One word.', pose: 'typing', think: 'Done.', bg: 'cyan' },
    p2: { cap: 'Meanwhile, a robot reads the page every hour. It looks for one word.', inst: 'robot', bg: 'yel' },
    q: { text: 'What does the robot do?', choices: ['Nothing. It\'s a robot.', 'Complains a little', 'Stops the whole release'], answer: 2 },
    splash: { cap: 'Ten minutes later.', inst: 'robot', sfx: 'HALT!', pose: 'phone', sub: 'The release is blocked. By a robot. Because of a word.' },
    w: { p1cap: 'You send the note. You go to lunch.', chat: [{who:'me',text:'Tiny job! Move it right, rename it Continue. 5 min?'},{who:'them',text:'On it 👍'}], sub: "Maya's release is blocked. You're having a sandwich.", text: "You didn't do anything wrong. You didn't know there was a robot. Nobody told you. That's the point." },
    reveal: { face: 'thinking', title: 'The robot only knows the old word.',
      text: 'It was told: find a button called "Submit". There isn\'t one. So it stops everything. You fix the robot in twenty minutes and ship. Fine.',
      take: 'Robots are promises about the past. Change the past, break the promise.' },
  },
  { id: 'counter', type: 'guess', title: 'The Counter',
    p1: { cap: 'Shipped. Feeling good.', pose: 'phone', think: 'Next.', bg: 'green' },
    p2: { cap: 'Far away, in a room nobody visits, a counter waits for one word: "Submit."', inst: 'counter', bg: 'yel' },
    q: { text: 'Next morning. What does the counter say?', choices: ['Same as always', 'A bit less', 'Zero'], answer: 2 },
    splash: { cap: 'Next morning.', inst: 'counter', sfx: 'SNAP!', pose: 'alarm', sub: 'Nothing crashed. Nothing beeped.' },
    w: { p1cap: 'Day 2. You check in.', chat: [{who:'me',text:'Button looks great! Thanks'},{who:'them',text:'👍'}], sub: 'Nothing crashed. Nothing beeped. Nobody messaged you.', text: "You asked for one word. The counter was listening for the old one. You couldn't have seen that from your side of the ticket." },
    reveal: { face: 'worried', title: 'The counter only knows one word.',
      text: 'People still click. The counter just can\'t hear them anymore. It says zero, and it isn\'t lying — nobody clicked "Submit" today.',
      take: 'Silence looks like "fine".' },
  },
  { id: 'calendar', type: 'guess', title: 'Who Notices',
    p1: { cap: 'Day 1. The counter reads zero. Nobody knows.', pose: 'typing', think: '…', bg: 'mag' },
    p2: { cap: 'Marketing opens the report once a month. Next one: day 22.', inst: 'calendar', bg: 'paper' },
    q: { text: 'When does anyone notice?', choices: ['Today', 'This week', 'Three weeks from now'], answer: 2 },
    splash: { cap: 'Day 22. Report day.', inst: 'calendar', sfx: 'WHAT?!', pose: 'alarm', sub: 'The report says the shop sold nothing for three weeks.' },
    w: { p1cap: "Day 1. You've moved on to the next thing.", chat: [{who:'me',text:'Also can we look at the footer sometime?'},{who:'them',text:'Sure'}], sub: 'Day 22. Your name is on the ticket.', text: 'The report says zero. Someone asks who changed the button. The answer is a note you sent three weeks ago and forgot.' },
    reveal: { face: 'shocked', title: 'Broken and noticed are different days.',
      text: 'It broke on day one. Someone found out on day twenty-two. Twenty-one days of a shop that looked closed. The gap in between is where the damage lives.',
      take: 'The worst bugs are quiet.' },
  },
  { id: 'voice', type: 'guess', title: 'The Voice',
    p1: { cap: 'Meanwhile, a customer who can\'t see the screen.', pose: 'phone', think: '', bg: 'blue' },
    p2: { cap: 'A voice reads the page out loud. It reads a hidden name, not the button.', inst: 'voice', bg: 'yel' },
    q: { text: 'What does the voice say?', choices: ['"Continue"', '"Submit"', 'Nothing'], answer: 1 },
    splash: { cap: 'The voice, faithfully.', inst: 'voice', sfx: 'HUH?', pose: 'phone', sub: '"Press Submit." There is no Submit.' },
    w: { p1cap: "A customer emails. They can't see the screen.", chat: [{who:'them',text:'The page tells me to press Submit. There is no Submit.'},{who:'me',text:'??'}], sub: "You've never heard the page read out loud.", text: 'There were two names on that button. You saw one. The customer heard the other.' },
    reveal: { face: 'worried', title: 'Every button has two names.',
      text: 'One you see. One you hear. You changed one. Blind customers are being told to press a button that isn\'t there.',
      take: 'What you see is half the button.' },
  },
  { id: 'shopDE', type: 'guess', title: 'The German Shop',
    p1: { cap: 'Same shop. German words.', pose: 'typing', think: 'Wait.', bg: 'yel' },
    p2: { cap: 'The German shop had one word for "Submit": Absenden.', inst: 'shopDE', bg: 'cyan' },
    q: { text: 'What\'s on the German button now?', choices: ['Fortfahren', 'Continue, in English', 'Still Absenden'], answer: 1 },
    splash: { cap: 'Two days later a translator sends "Fortfahren".', inst: 'shopDE', sfx: 'KRRK!', pose: 'slumped', sub: 'It doesn\'t fit the box.' },
    w: { p1cap: 'A colleague in Berlin pings you.', chat: [{who:'them',text:'Why is checkout in English now?'},{who:'me',text:'It should say Fortfahren?'},{who:'them',text:"Doesn't fit."}], sub: "You didn't ask for the German shop. It came with the button.", text: 'One button, twelve languages. You changed one word in one of them.' },
    reveal: { face: 'exhausted', title: 'One word, two problems.',
      text: 'First the word didn\'t exist. Then it did, and it was too long. German is about a third longer than English. The button was sized for six letters.',
      take: 'A new word in one language is a missing word in every other.' },
  },
  { id: 'mirror', type: 'guess', title: 'The Mirror',
    p1: { cap: 'You moved the button to the right.', pose: 'phone', think: 'Right?', bg: 'mag' },
    p2: { cap: 'The Arabic shop reads right-to-left. It mirrors the whole page.', inst: 'mirror', bg: 'paper' },
    q: { text: 'Where is the button for Arabic readers?', choices: ['Right', 'Left'], answer: 1 },
    splash: { cap: 'Mirrored.', inst: 'mirror', sfx: 'FLIP!', pose: 'phone', sub: 'Was that what you wanted? Nobody asked.' },
    w: { p1cap: 'You said "right". Someone asks what you meant.', chat: [{who:'them',text:'Right for Arabic too, or mirrored?'},{who:'me',text:"…I don't know."}], sub: 'Nobody asked. So the mirror decided.', text: "Part of what you asked for wasn't a fix. It was a question with no answer yet." },
    reveal: { face: 'thinking', title: 'Some strings aren\'t bugs.',
      text: 'They\'re questions. "Right" in a mirror is "left". Maybe that\'s right. Maybe not. Nobody decided, so the mirror decided.',
      take: 'Some wires are a conversation, not a fix.' },
  },
  { id: 'article', type: 'guess', title: 'The Help Page',
    p1: { cap: 'Support has a help page. It describes the button in words.', pose: 'typing', think: 'Oh no.', bg: 'cyan' },
    p2: { cap: 'The help page still says "Submit", "left".', inst: 'article', bg: 'yel' },
    q: { text: 'Support gets an email. What does it say?', choices: ['"Love the new button!"', '"There is no Submit button."', '"Why is checkout in German?"'], answer: 1 },
    splash: { cap: 'Support inbox.', inst: 'article', sfx: 'DING!', pose: 'slumped', sub: 'Fourteen emails. Nobody told support either.' },
    w: { p1cap: 'Support forwards you an email.', chat: [{who:'them',text:'14 tickets today: "there is no Submit button"'}], sub: 'The help page still says Submit. Nobody told support. Including you.', text: 'The button lived in a help page, a video, a support script. You changed the screen. The rest stayed.' },
    reveal: { face: 'exhausted', title: 'Words about the button are also wires.',
      text: 'Help pages, videos, support scripts, training slides. Every one of them said "Submit". Every one is now wrong.',
      take: 'The button lives in more places than the screen.' },
  },
  { id: 'end', type: 'end' },
];
